In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import FactorAnalysis as fa
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3


In [4]:
X = df.drop("species",axis=1)
y = df["species"]

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state=4)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [8]:
explained_varience = pca.explained_variance_ratio_
explained_varience

array([0.75622882, 0.18893543, 0.04151166, 0.00887797, 0.00444611])

In [9]:
def perfrom_pca(n):
    X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
    pca = PCA(n_components=n)
    pca_x_train = pca.fit_transform(X_train)
    pca_x_test = pca.transform(X_test)
    classifier = RandomForestClassifier(max_depth=2, random_state=0)
    classifier.fit(pca_x_train, y_train)
    y_pred = classifier.predict(pca_x_test)
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    print('Accuracy {0}\n\n'.format(accuracy_score(y_test, y_pred)))

In [10]:
for n in range(1,5):perfrom_pca(n)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Accuracy 0.9666666666666667


[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy 1.0


[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy 1.0


[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy 1.0


